"""add_email_verification_otps

Revision ID: a5067904e0f3
Revises: cd37ce6224a6
Create Date: 2026-09-11 16:14:35.100847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5067904e0f3'
down_revision = 'cd37ce6224a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_otps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_otps_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_otps_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_otps_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_otps_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_verification_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_otps_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_otps_purpose'))
        batch_op.drop_index(batch_op.f('ix_email_verification_otps_expires_at'))
        batch_op.drop_index(batch_op.f('ix_email_verification_otps_email'))

    op.drop_table('email_verification_otps')
    # ### end Alembic commands ###
