"""initial_neon_production_schema

Revision ID: cd37ce6224a6
Revises: 
Create Date: 2026-09-11 16:01:22.642755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd37ce6224a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_exams_is_active'), ['is_active'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('target_exam', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('daily_goal', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_target_exam'), ['target_exam'], unique=False)

    op.create_table('achievements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_user_achievement_code')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('admin_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('action_name', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_actions_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_created_at'), ['created_at'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('context_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('ai_usage_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_logs_user_id'), ['user_id'], unique=False)

    op.create_table('daily_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_questions', sa.Integer(), nullable=True),
    sa.Column('target_study_minutes', sa.Integer(), nullable=True),
    sa.Column('solved_today', sa.Integer(), nullable=True),
    sa.Column('minutes_today', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_achieved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_daily_goal_date')
    )
    with op.batch_alter_table('daily_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_goals_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_goals_is_achieved'), ['is_achieved'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_goals_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_questions_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('question_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exam_id', sa.String(length=36), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('set_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_sets_exam_id'), ['exam_id'], unique=False)

    op.create_table('streaks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streaks_user_id'), ['user_id'], unique=True)

    op.create_table('test_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_type', sa.String(length=30), nullable=True),
    sa.Column('exam_id', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('incorrect_count', sa.Integer(), nullable=True),
    sa.Column('unattempted_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_session_type'), ['session_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('importance_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_subject_id'), ['subject_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('college_or_institute', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('preferred_exam_categories', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('user_topic_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('incorrect_count', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('avg_time_seconds', sa.Float(), nullable=True),
    sa.Column('weakness_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic_stats')
    )
    with op.batch_alter_table('user_topic_stats', schema=None) as batch_op:
        batch_op.create_index('idx_topic_stats_weakness', ['user_id', 'weakness_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_topic_stats_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_topic_stats_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_topic_stats_weakness_score'), ['weakness_score'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_sections', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_created_at'), ['created_at'], unique=False)

    op.create_table('document_processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('extracted_count', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_processing_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_processing_jobs_status'), ['status'], unique=False)

    op.create_table('focus_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_events_user_id'), ['user_id'], unique=False)

    op.create_table('pdf_question_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('candidate_answer', sa.String(length=10), nullable=True),
    sa.Column('has_explicit_answer', sa.Boolean(), nullable=True),
    sa.Column('answer_status', sa.String(length=30), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pdf_question_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_question_drafts_answer_status'), ['answer_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_question_drafts_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_question_drafts_is_imported'), ['is_imported'], unique=False)

    op.create_table('subtopics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subtopics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtopics_topic_id'), ['topic_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('subtopic_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=150), nullable=False),
    sa.Column('subtopic', sa.String(length=150), nullable=True),
    sa.Column('exam', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('question_type', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('answer_status', sa.String(length=30), nullable=True),
    sa.Column('answer_confidence', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('idx_questions_exam_subject_diff', ['exam', 'subject', 'difficulty'], unique=False)
        batch_op.create_index('idx_questions_topic_verified', ['topic_id', 'is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_answer_status'), ['answer_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_exam'), ['exam'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_source_document_id'), ['source_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subtopic_id'), ['subtopic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)

    op.create_table('answer_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('verified_by_model', sa.String(length=100), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('source_citations', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_verifications_question_id'), ['question_id'], unique=False)

    op.create_table('bookmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question_bookmark')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_user_id'), ['user_id'], unique=False)

    op.create_table('mistakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=100), nullable=True),
    sa.Column('first_mistake_at', sa.DateTime(), nullable=False),
    sa.Column('last_mistake_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('repeated_mistakes_count', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question_mistake')
    )
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.create_index('idx_mistakes_user_resolved', ['user_id', 'is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistakes_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistakes_last_mistake_at'), ['last_mistake_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistakes_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistakes_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistakes_user_id'), ['user_id'], unique=False)

    op.create_table('question_exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'exam_id', name='uq_question_exam')
    )
    with op.batch_alter_table('question_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_exams_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_exams_question_id'), ['question_id'], unique=False)

    op.create_table('question_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('option_key', sa.String(length=10), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.create_index('idx_qopt_question_key', ['question_id', 'option_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)

    op.create_table('question_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('reference_citation', sa.String(length=255), nullable=True),
    sa.Column('exam_year', sa.Integer(), nullable=True),
    sa.Column('paper_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_sources_question_id'), ['question_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('test_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option', sa.String(length=10), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_answers', schema=None) as batch_op:
        batch_op.create_index('idx_test_answers_user_correct', ['user_id', 'correct'], unique=False)
        batch_op.create_index('idx_test_answers_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_answers_correct'), ['correct'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_answers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_answers_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_answers_user_id'), ['user_id'], unique=False)

    op.create_table('test_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.create_index('idx_test_question_session_order', ['session_id', 'order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_questions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_questions_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_questions_session_id'))
        batch_op.drop_index(batch_op.f('ix_test_questions_question_id'))
        batch_op.drop_index('idx_test_question_session_order')

    op.drop_table('test_questions')
    with op.batch_alter_table('test_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_test_answers_session_id'))
        batch_op.drop_index(batch_op.f('ix_test_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_test_answers_created_at'))
        batch_op.drop_index(batch_op.f('ix_test_answers_correct'))
        batch_op.drop_index('idx_test_answers_user_created')
        batch_op.drop_index('idx_test_answers_user_correct')

    op.drop_table('test_answers')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_question_id'))

    op.drop_table('reports')
    with op.batch_alter_table('question_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_sources_question_id'))

    op.drop_table('question_sources')
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_options_question_id'))
        batch_op.drop_index('idx_qopt_question_key')

    op.drop_table('question_options')
    with op.batch_alter_table('question_exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_exams_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_exams_exam_id'))

    op.drop_table('question_exams')
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mistakes_user_id'))
        batch_op.drop_index(batch_op.f('ix_mistakes_topic_id'))
        batch_op.drop_index(batch_op.f('ix_mistakes_question_id'))
        batch_op.drop_index(batch_op.f('ix_mistakes_last_mistake_at'))
        batch_op.drop_index(batch_op.f('ix_mistakes_is_resolved'))
        batch_op.drop_index('idx_mistakes_user_resolved')

    op.drop_table('mistakes')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_question_id'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_created_at'))

    op.drop_table('bookmarks')
    with op.batch_alter_table('answer_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_verifications_question_id'))

    op.drop_table('answer_verifications')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_questions_topic'))
        batch_op.drop_index(batch_op.f('ix_questions_subtopic_id'))
        batch_op.drop_index(batch_op.f('ix_questions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_questions_subject'))
        batch_op.drop_index(batch_op.f('ix_questions_source_type'))
        batch_op.drop_index(batch_op.f('ix_questions_source_document_id'))
        batch_op.drop_index(batch_op.f('ix_questions_question_type'))
        batch_op.drop_index(batch_op.f('ix_questions_language'))
        batch_op.drop_index(batch_op.f('ix_questions_is_verified'))
        batch_op.drop_index(batch_op.f('ix_questions_exam'))
        batch_op.drop_index(batch_op.f('ix_questions_difficulty'))
        batch_op.drop_index(batch_op.f('ix_questions_answer_status'))
        batch_op.drop_index('idx_questions_topic_verified')
        batch_op.drop_index('idx_questions_exam_subject_diff')

    op.drop_table('questions')
    with op.batch_alter_table('subtopics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtopics_topic_id'))

    op.drop_table('subtopics')
    with op.batch_alter_table('pdf_question_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_question_drafts_is_imported'))
        batch_op.drop_index(batch_op.f('ix_pdf_question_drafts_document_id'))
        batch_op.drop_index(batch_op.f('ix_pdf_question_drafts_answer_status'))

    op.drop_table('pdf_question_drafts')
    with op.batch_alter_table('focus_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_focus_events_session_id'))

    op.drop_table('focus_events')
    with op.batch_alter_table('document_processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_document_processing_jobs_document_id'))

    op.drop_table('document_processing_jobs')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('user_topic_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_topic_stats_weakness_score'))
        batch_op.drop_index(batch_op.f('ix_user_topic_stats_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_topic_stats_topic_id'))
        batch_op.drop_index('idx_topic_stats_weakness')

    op.drop_table('user_topic_stats')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_subject_id'))
        batch_op.drop_index(batch_op.f('ix_topics_name'))

    op.drop_table('topics')
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_session_type'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_exam_id'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_created_at'))

    op.drop_table('test_sessions')
    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streaks_user_id'))

    op.drop_table('streaks')
    with op.batch_alter_table('question_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_sets_exam_id'))

    op.drop_table('question_sets')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))

    op.drop_table('documents')
    with op.batch_alter_table('daily_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_goals_is_achieved'))
        batch_op.drop_index(batch_op.f('ix_daily_goals_date'))

    op.drop_table('daily_goals')
    with op.batch_alter_table('ai_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_logs_created_at'))

    op.drop_table('ai_usage_logs')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_admin_user_id'))

    op.drop_table('admin_actions')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_user_id'))

    op.drop_table('achievements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_target_exam'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_name'))

    op.drop_table('subjects')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_is_active'))
        batch_op.drop_index(batch_op.f('ix_exams_code'))
        batch_op.drop_index(batch_op.f('ix_exams_category'))

    op.drop_table('exams')
    # ### end Alembic commands ###
