"""add learning experience models

Revision ID: f1670238de01
Revises: f57b39bbf265
Create Date: 2026-09-11 16:35:16.791716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1670238de01'
down_revision = 'f57b39bbf265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_current_affairs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=150), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('exam_relevance', sa.String(length=100), nullable=True),
    sa.Column('key_takeaways', sa.JSON(), nullable=True),
    sa.Column('question_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_current_affairs', schema=None) as batch_op:
        batch_op.create_index('idx_current_affairs_date_topic', ['date', 'topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_current_affairs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_current_affairs_exam_relevance'), ['exam_relevance'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_current_affairs_topic'), ['topic'], unique=False)

    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skipped_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('focus_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('focus_violations_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_coach_summary', sa.JSON(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_bests', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('personal_bests')

    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('ai_coach_summary')
        batch_op.drop_column('focus_violations_count')
        batch_op.drop_column('focus_score')
        batch_op.drop_column('skipped_count')
        batch_op.drop_column('time_limit_seconds')

    with op.batch_alter_table('daily_current_affairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_current_affairs_topic'))
        batch_op.drop_index(batch_op.f('ix_daily_current_affairs_exam_relevance'))
        batch_op.drop_index(batch_op.f('ix_daily_current_affairs_date'))
        batch_op.drop_index('idx_current_affairs_date_topic')

    op.drop_table('daily_current_affairs')
    # ### end Alembic commands ###
