"""enhance_pdf_engine_models

Revision ID: f57b39bbf265
Revises: a5067904e0f3
Create Date: 2026-09-11 16:21:53.402076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57b39bbf265'
down_revision = 'a5067904e0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('processing_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ready_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('needs_review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duplicate_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_processing_stage'), ['processing_stage'], unique=False)

    with op.batch_alter_table('pdf_question_drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('verification_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('verification_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('explanation_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_duplicate', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('duplicate_of_question_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_pdf_question_drafts_is_duplicate'), ['is_duplicate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_question_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_question_drafts_is_duplicate'))
        batch_op.drop_column('topic')
        batch_op.drop_column('subject')
        batch_op.drop_column('language')
        batch_op.drop_column('duplicate_of_question_id')
        batch_op.drop_column('is_duplicate')
        batch_op.drop_column('explanation_json')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_notes')
        batch_op.drop_column('verification_source')
        batch_op.drop_column('question_image_url')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_processing_stage'))
        batch_op.drop_index(batch_op.f('ix_documents_file_hash'))
        batch_op.drop_column('duplicate_count')
        batch_op.drop_column('needs_review_count')
        batch_op.drop_column('ready_count')
        batch_op.drop_column('processing_stage')
        batch_op.drop_column('file_hash')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
